var Lang_ISO_639_1 ={"ab":"ab - Abkhaz",
		"aa":"aa - Afar",
		"af":"af - Afrikaans",
		"ak":"ak - Akan",
		"sq":"sq - Albanian",
		"am":"am - Amharic",
		"ar":"ar - Arabic",
		"an":"an - Aragonese",
		"hy":"hy - Armenian",
		"as":"as - Assamese",
		"av":"av - Avaric",
		"ae":"ae - Avestan",
		"ay":"ay - Aymara",
		"az":"az - Azerbaijani",
		"bm":"bm - Bambara",
		"ba":"ba - Bashkir",
		"eu":"eu - Basque",
		"be":"be - Belarusian",
		"bn":"bn - Bengali, Bangla",
		"bh":"bh - Bihari",
		"bi":"bi - Bislama",
		"bs":"bs - Bosnian",
		"br":"br - Breton",
		"bg":"bg - Bulgarian",
		"my":"my - Burmese",
		"ca":"ca - Catalan",
		"ch":"ch - Chamorro",
		"ce":"ce - Chechen",
		"ny":"ny - Chichewa, Chewa, Nyanja",
		"zh":"zh - Chinese",
		"cv":"cv - Chuvash",
		"kw":"kw - Cornish",
		"co":"co - Corsican",
		"cr":"cr - Cree",
		"hr":"hr - Croatian",
		"cs":"cs - Czech",
		"da":"da - Danish",
		"dv":"dv - Divehi, Dhivehi, Maldivian",
		"nl":"nl - Dutch",
		"dz":"dz - Dzongkha",
		"en":"en - English",
		"eo":"eo - Esperanto",
		"et":"et - Estonian",
		"ee":"ee - Ewe",
		"fo":"fo - Faroese",
		"fj":"fj - Fijian",
		"fi":"fi - Finnish",
		"fr":"fr - French",
		"ff":"ff - Fula, Fulah, Pulaar, Pular",
		"gl":"gl - Galician",
		"ka":"ka - Georgian",
		"de":"de - German",
		"el":"el - Greek (modern)",
		"gn":"gn - Guaraní",
		"gu":"gu - Gujarati",
		"ht":"ht - Haitian, Haitian Creole",
		"ha":"ha - Hausa",
		"he":"he - Hebrew (modern)",
		"hz":"hz - Herero",
		"hi":"hi - Hindi",
		"ho":"ho - Hiri Motu",
		"hu":"hu - Hungarian",
		"ia":"ia - Interlingua",
		"id":"id - Indonesian",
		"ie":"ie - Interlingue",
		"ga":"ga - Irish",
		"ig":"ig - Igbo",
		"ik":"ik - Inupiaq",
		"io":"io - Ido",
		"is":"is - Icelandic",
		"it":"it - Italian",
		"iu":"iu - Inuktitut",
		"ja":"ja - Japanese",
		"jv":"jv - Javanese",
		"kl":"kl - Kalaallisut, Greenlandic",
		"kn":"kn - Kannada",
		"kr":"kr - Kanuri",
		"ks":"ks - Kashmiri",
		"kk":"kk - Kazakh",
		"km":"km - Khmer",
		"ki":"ki - Kikuyu, Gikuyu",
		"rw":"rw - Kinyarwanda",
		"ky":"ky - Kyrgyz",
		"kv":"kv - Komi",
		"kg":"kg - Kongo",
		"ko":"ko - Korean",
		"ku":"ku - Kurdish",
		"kj":"kj - Kwanyama, Kuanyama",
		"la":"la - Latin",
		"lb":"lb - Luxembourgish, Letzeburgesch",
		"lg":"lg - Ganda",
		"li":"li - Limburgish, Limburgan, Limburger",
		"ln":"ln - Lingala",
		"lo":"lo - Lao",
		"lt":"lt - Lithuanian",
		"lu":"lu - Luba-Katanga",
		"lv":"lv - Latvian",
		"gv":"gv - Manx",
		"mk":"mk - Macedonian",
		"mg":"mg - Malagasy",
		"ms":"ms - Malay",
		"ml":"ml - Malayalam",
		"mt":"mt - Maltese",
		"mi":"mi - Maori",
		"mr":"mr - Marathi (Mara?hi)",
		"mh":"mh - Marshallese",
		"mn":"mn - Mongolian",
		"na":"na - Nauru",
		"nv":"nv - Navajo, Navaho",
		"nd":"nd - Northern Ndebele",
		"ne":"ne - Nepali",
		"ng":"ng - Ndonga",
		"nb":"nb - Norwegian Bokmål",
		"nn":"nn - Norwegian Nynorsk",
		"no":"no - Norwegian",
		"ii":"ii - Nuosu",
		"nr":"nr - Southern Ndebele",
		"oc":"oc - Occitan",
		"oj":"oj - Ojibwe, Ojibwa",
		"cu":"cu - Old Church Slavonic, Church Slavonic, Old Bulgarian",
		"om":"om - Oromo",
		"or":"or - Oriya",
		"os":"os - Ossetian, Ossetic",
		"pa":"pa - Panjabi, Punjabi",
		"pi":"pi - Pali",
		"fa":"fa - Persian (Farsi)",
		"pl":"pl - Polish",
		"ps":"ps - Pashto, Pushto",
		"pt":"pt - Portuguese",
		"qu":"qu - Quechua",
		"rm":"rm - Romansh",
		"rn":"rn - Kirundi",
		"ro":"ro - Romanian",
		"ru":"ru - Russian",
		"sa":"sa - Sanskrit",
		"sc":"sc - Sardinian",
		"sd":"sd - Sindhi",
		"se":"se - Northern Sami",
		"sm":"sm - Samoan",
		"sg":"sg - Sango",
		"sr":"sr - Serbian",
		"gd":"gd - Scottish Gaelic, Gaelic",
		"sn":"sn - Shona",
		"si":"si - Sinhala, Sinhalese",
		"sk":"sk - Slovak",
		"sl":"sl - Slovene",
		"so":"so - Somali",
		"st":"st - Southern Sotho",
		"es":"es - Spanish",
		"su":"su - Sundanese",
		"sw":"sw - Swahili",
		"ss":"ss - Swati",
		"sv":"sv - Swedish",
		"ta":"ta - Tamil",
		"te":"te - Telugu",
		"tg":"tg - Tajik",
		"th":"th - Thai",
		"ti":"ti - Tigrinya",
		"bo":"bo - Tibetan Standard, Tibetan, Central",
		"tk":"tk - Turkmen",
		"tl":"tl - Tagalog",
		"tn":"tn - Tswana",
		"to":"to - Tonga (Tonga Islands)",
		"tr":"tr - Turkish",
		"ts":"ts - Tsonga",
		"tt":"tt - Tatar",
		"tw":"tw - Twi",
		"ty":"ty - Tahitian",
		"ug":"ug - Uyghur",
		"uk":"uk - Ukrainian",
		"ur":"ur - Urdu",
		"uz":"uz - Uzbek",
		"ve":"ve - Venda",
		"vi":"vi - Vietnamese",
		"vo":"vo - Volapük",
		"wa":"wa - Walloon",
		"cy":"cy - Welsh",
		"wo":"wo - Wolof",
		"fy":"fy - Western Frisian",
		"xh":"xh - Xhosa",
		"yi":"yi - Yiddish",
		"yo":"yo - Yoruba",
		"za":"za - Zhuang, Chuang",
		"zu":"zu - Zulu",
};